image: ruby:2.1

pipelines:
  default:
    - step:
        name: Ruby 2.1
        image: ruby:2.1
        script:
          - ruby --version
          - bundle --version
          - bundle install
          - bundle exec rake spec:offline
          - bundle exec rake build
    - step:
        name: Ruby 2.3
        image: ruby:2.3
        script:
          - ruby --version
          - bundle --version
          - bundle install
          - bundle exec rake spec:offline
          - bundle exec rake build
    - step:
        name: Ruby 2.4
        image: ruby:2.4
        script:
          - ruby --version
          - bundle --version
          - bundle install
          - bundle exec rake spec:offline
          - bundle exec rake build
