image: ruby:2.1.0

pipelines:
  default:
    - step:
        script:
          - bundler --version
          - bundle install
          - bundle exec rake spec:offline
          - bundle exec rake build